### PR TITLE
Patch h2 v0.4.0 for WasmEdge

### PR DESCRIPTION
**Pull request by 0xE282B0**
This PR is based on h2 v0.4.0 and rebases the changes for usage with WasmEdge from the `master` branch.
Unfortunately, due to the rebase this is not fast-forward.

To avoid conflicts we could create a separate branch and tag for v0.4.0.
What do you think?

### CODE REVIEW

**Comment by L-jasmine** [comment]
@0xE282B0 Thanks for the pull request!  Before we can merge this, we need you to sign off on each commit in the pull request.  Please add your sign-off to each commit using the --signoff option when making commits.  This indicates that you agree to the Developer Certificate of Origin (DCO).

**Comment by 0xE282B0** [comment]
Hello,
Most of the commits are rebased from the upstream project. But I can add a signoff 😊.

**Comment by 0xE282B0** [comment]
Rebased with signoff.

**Comment by L-jasmine** [comment]
The 'client' and 'server' examples in the 'examples' folder are fine, but the 'akamai' example cannot compile successfully. This is because its dependency, 'tokio_rustls,' uses 'tokio' instead of 'tokio_wasi.' 

Yes, there are many dependencies that need to be adjusted upwards, so we are currently working on finding a solution to this problem.

**Review by L-jasmine — APPROVED** [review]

**Pull request merged**
